In [1]:
from modules import capital_prices

capital_prices('Spain')

/Applications/anaconda3/envs/thesis/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

   country  year  capitalprice
0    Spain  1992         0.658
1    Spain  1993         0.672
2    Spain  1994         0.689
3    Spain  1995         0.717
4    Spain  1996         0.737
5    Spain  1997         0.746
6    Spain  1998         0.753
7    Spain  1999         0.759
8    Spain  2000         0.769
9    Spain  2001         0.779
10   Spain  2002         0.793
11   Spain  2003         0.803
12   Spain  2004         0.814
13   Spain  2005         0.830
14   Spain  2006         0.855
15   Spain  2007         0.884
16   Spain  2008         0.906
17   Spain  2009         0.913
18   Spain  2010         0.917
19   Spain  2011         0.926
20   Spain  2012         0.931
21   Spain  2013         0.930
22   Spain  2014         0.932
23   Spain  2015         1.000
24   Spain  2016         0.945
25   Spain  2017         0.953
26   Spain  2018         0.962
27   Spain  2019         0.971
28   Spain  2020         0.980
29   Spain  2021         1.000
30   Spain  2022         1.054
31   Spain  2023         1.088
32   Spain  2024         1.111
33   Spain  2025         1.131

/Applications/anaconda3/envs/thesis/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Applications/anaconda3/envs/thesis/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

   country  year  nominalinterestrate  inflation  realinterestrate
0    Spain  1996             0.087400        NaN               NaN
1    Spain  1997             0.064000      0.019          0.045000
2    Spain  1998             0.048300      0.018          0.030300
3    Spain  1999             0.047300      0.022          0.025300
4    Spain  2000             0.055300      0.035          0.020300
5    Spain  2001             0.051200      0.028          0.023200
6    Spain  2002             0.049600      0.036          0.013600
7    Spain  2003             0.041200      0.031          0.010200
8    Spain  2004             0.041000      0.031          0.010000
9    Spain  2005             0.033900      0.034         -0.000100
10   Spain  2006             0.037800      0.036          0.001800
11   Spain  2007             0.043100      0.028          0.015100
12   Spain  2008             0.043700      0.041          0.002700
13   Spain  2009             0.039800     -0.002          0.041800
14   Spain  2010             0.042500      0.020          0.022500
15   Spain  2011             0.054400      0.031          0.023400
16   Spain  2012             0.058500      0.024          0.034500
17   Spain  2013             0.045600      0.015          0.030600
18   Spain  2014             0.027200     -0.002          0.029200
19   Spain  2015             0.017300     -0.006          0.023300
20   Spain  2016             0.013900     -0.003          0.016900
21   Spain  2017             0.015600      0.020         -0.004400
22   Spain  2018             0.014200      0.017         -0.002800
23   Spain  2019             0.006600      0.008         -0.001400
24   Spain  2020             0.003800     -0.003          0.006800
25   Spain  2021             0.003500      0.030         -0.026500
26   Spain  2022             0.021800      0.083         -0.061200
27   Spain  2023             0.034800      0.034          0.000800
28   Spain  2024             0.031500      0.029          0.002500
29   Spain  2025             0.032138      0.027          0.005138